/* SPARKED Signal Run. Road-projection architecture adapted from the MIT-licensed
   jakesgordon/javascript-racer project. SPARKED visuals and content are original. */
(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const drivers=[['IZZY MONROE','IM','CURRENT RUNNER','ROUTE CURRENT','Finds the clearest way through the blackout.'],['AALIYAH GAIN','AG','VELOCITY','ACCELERATE','Turns every open street into an advantage.'],['THEO REED','TR','POWER LINE','BREAKAWAY','Keeps the rescue run moving forward.'],['JORDAN KIM','JK','SIGNAL TECH','OVERRIDE','Reads the city faster than it can close in.'],['MATEO RIVERA','MR','STREETWISE','SHORTCUT','Knows which streets still lead home.']];
const cars=[['VOLT GT','#50e7ed',184,'Twin-turbo street coupé',0],['NIGHTFALL R','#a47aff',176,'Low-slung grand tourer',68],['SUNFIRE ZX','#ff5b9e',191,'Lightweight sport compact',-48],['RIVET 4X','#ffbd4d',171,'All-weather rally machine',32]];
const routes=[['LAKEFRONT ESCAPE','Aldermoor → Lakefront Safe Zone','lakefront','Two laps · wet boulevard · marina lights','./art2d/lakefront.png'],['CASINO CAUSEWAY','Founders Square → Salk Bingo and Casino','casino','Two laps · tunnel sweep · casino express','./art2d/casino.png'],['LAMBEAU NIGHT RUN','Lambeau High → Clearview','lambeau','Two laps · stadium hill · lake curve','./art2d/lambeau.png']];
const state={driver:0,car:0,route:0,racing:false,paused:false,position:0,speed:0,x:0,boost:100,passes:0,keys:{},segments:[],traffic:[],track:0};
const canvas=$('#driveCanvas'),ctx=canvas.getContext('2d'),carArt=new Image(),backdrops=routes.map(r=>{const i=new Image();i.src=r[4];return i});carArt.src='./art2d/volt-gt.png';
const SEGMENT=200,ROAD=2000,CAMERA_H=1000,CAMERA_D=1/Math.tan(Math.PI/3.15),PLAYER_Z=CAMERA_H*CAMERA_D,DRAW=180;let width=1,height=1,dpr=1,last=performance.now();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),increase=(v,n,max)=>(v+n)%max,interp=(a,b,p)=>a+(b-a)*p,percent=(n,total)=>(n%total)/total;
function resize(){dpr=Math.min(devicePixelRatio||1,2);width=canvas.clientWidth||innerWidth;height=canvas.clientHeight||innerHeight;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function selectUI(){$('#drivers').innerHTML=drivers.map((d,i)=>`<button type="button" class="pick ${i===state.driver?'selected':''}" data-driver="${i}"><span class="tag">${d[2]}</span><span class="initial">${d[1]}</span><h3>${d[0]}</h3><p>${d[4]}</p><small class="ability">⚡ ${d[3]}</small></button>`).join('');$('#cars').innerHTML=cars.map((c,i)=>`<button type="button" class="pick car-pick ${i===state.car?'selected':''}" data-car="${i}"><img src="./art2d/volt-gt.png" alt="${c[0]}"><span class="tag">ORIGINAL 1999 SPORTS CAR</span><h3>${c[0]}</h3><p>${c[3]}</p><div class="stat">TOP ${c[2]} MPH<br>GRIP ${'▮'.repeat(3+i%2)}</div></button>`).join('');$('#routeCards').innerHTML=routes.map((r,i)=>`<button type="button" class="route-card ${i===state.route?'selected':''}" data-route="${i}" style="--route-img:url('${r[4]}')"><div><span class="tag">${r[3].toUpperCase()}</span><h3>${r[0]}</h3><p>${r[1]}</p><small>12 CHECKPOINTS · PASSENGER ABOARD FROM START</small></div></button>`).join('');$$('[data-driver]').forEach(b=>b.onclick=()=>{state.driver=+b.dataset.driver;selectUI()});$$('[data-car]').forEach(b=>b.onclick=()=>{state.car=+b.dataset.car;selectUI()});$$('[data-route]').forEach(b=>b.onclick=()=>{state.route=+b.dataset.route;selectUI()})}selectUI();
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));if(id!=='none')$('#'+id).classList.add('active')}window.sparkedShow=show;document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(b){e.preventDefault();show(b.dataset.screen)}});
function lastY(){return state.segments.length?state.segments.at(-1).p2.y:0}function addSegment(curve,y){const n=state.segments.length;state.segments.push({index:n,curve,p1:{y:lastY(),z:n*SEGMENT},p2:{y,z:(n+1)*SEGMENT},cars:[]})}function road(enter,hold,leave,curve,hill){const start=lastY(),end=start+hill*SEGMENT,total=enter+hold+leave;for(let n=0;n<total;n++){const p=n<enter?(n/enter)**2:n<enter+hold?1:(1-(n-enter-hold)/leave)**2;addSegment(curve*p,interp(start,end,n/total))}}
function buildRoad(){state.segments=[];const profile=state.route===0?[[25,30,25,1.2,14],[35,35,30,-2.8,-9],[25,38,25,2.2,18],[50,50,40,-1.4,-12]]:state.route===1?[[24,36,24,3.4,5],[40,48,32,-3.7,-18],[32,28,28,2.6,24],[55,45,42,-2.1,-14]]:[[28,34,22,-2.8,30],[30,45,34,3.6,-23],[44,44,36,-3.1,17],[55,55,38,1.9,-22]];for(let lap=0;lap<2;lap++)for(const p of profile){road(...p);road(18,22,18,0,0)}road(22,28,22,0,-lastY()/SEGMENT);state.track=state.segments.length*SEGMENT}function segmentAt(z){return state.segments[Math.floor(z/SEGMENT)%state.segments.length]}
function buildTraffic(){state.traffic=[];const lanes=[-.7,-.35,.12,.52,.78];for(let n=0;n<18;n++){const z=(n*state.track/18+5000)%state.track,car={z,offset:lanes[n%lanes.length]+(n%3-1)*.06,speed:78+(n%6)*13,hue:[34,126,282,184,8][n%5],passed:false};state.traffic.push(car);segmentAt(z).cars.push(car)}}
function launch(){buildRoad();buildTraffic();Object.assign(state,{racing:true,paused:false,position:0,speed:72,x:0,boost:100,passes:0,keys:{}});$('#app').className='route-'+routes[state.route][2]+' engine-running';$('#routeName').textContent=routes[state.route][0];$('#hud').hidden=false;$('#boostHud').hidden=false;$('#touch').hidden=innerWidth>720;$('#countdown').classList.remove('show');show('none');updateHud()}
function project(point,cx,cy,cz){const z=point.z-cz,scale=CAMERA_D/z;return{x:(1+scale*(point.x-cx))*width/2,y:(1-scale*(point.y-cy))*height/2,w:scale*ROAD*width/2,scale,z}}function poly(a,b,c,d,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.closePath();ctx.fill()}function cover(image){if(!image.complete||!image.naturalWidth)return;const s=Math.max(width/image.naturalWidth,height/image.naturalHeight),iw=image.naturalWidth*s,ih=image.naturalHeight*s;ctx.drawImage(image,(width-iw)/2,(height-ih)/2,iw,ih)}
function render(){ctx.clearRect(0,0,width,height);if(!state.racing)return;cover(backdrops[state.route]);ctx.fillStyle='rgba(5,7,20,.30)';ctx.fillRect(0,0,width,height);const base=segmentAt(state.position),baseP=percent(state.position,SEGMENT),player=segmentAt(state.position+PLAYER_Z),playerY=interp(player.p1.y,player.p2.y,percent(state.position+PLAYER_Z,SEGMENT));let x=0,dx=-(base.curve*baseP),clip=height,drawn=[];for(let n=0;n<DRAW;n++){const seg=state.segments[(base.index+n)%state.segments.length],looped=seg.index<base.index,cz=state.position-(looped?state.track:0),p1=project({x:0,y:seg.p1.y,z:seg.p1.z},state.x*ROAD-x,playerY+CAMERA_H,cz),p2=project({x:0,y:seg.p2.y,z:seg.p2.z},state.x*ROAD-x-dx,playerY+CAMERA_H,cz);x+=dx;dx+=seg.curve;if(p1.z<=CAMERA_D||p2.y>=p1.y||p2.y>=clip)continue;drawn.push({seg,p1,p2});clip=p1.y}for(let n=drawn.length-1;n>=0;n--){const {seg,p1,p2}=drawn[n],band=Math.floor(seg.index/3)%2,roadColor=band?'#101625':'#171c2d',rumble=band?'#faad46':'#a8478c';poly({x:p1.x-p1.w,y:p1.y},{x:p1.x+p1.w,y:p1.y},{x:p2.x+p2.w,y:p2.y},{x:p2.x-p2.w,y:p2.y},roadColor);poly({x:p1.x-p1.w*1.08,y:p1.y},{x:p1.x-p1.w,y:p1.y},{x:p2.x-p2.w,y:p2.y},{x:p2.x-p2.w*1.08,y:p2.y},rumble);poly({x:p1.x+p1.w,y:p1.y},{x:p1.x+p1.w*1.08,y:p1.y},{x:p2.x+p2.w*1.08,y:p2.y},{x:p2.x+p2.w,y:p2.y},rumble);if(seg.index%6<3)for(const lane of[-1/3,1/3])poly({x:p1.x+p1.w*lane-2,y:p1.y},{x:p1.x+p1.w*lane+2,y:p1.y},{x:p2.x+p2.w*lane+3,y:p2.y},{x:p2.x+p2.w*lane-3,y:p2.y},'rgba(255,245,195,.85)')}const visible=[];for(const car of state.traffic){const rel=(car.z-state.position+state.track)%state.track;if(rel>0&&rel<DRAW*SEGMENT)visible.push({car,rel})}visible.sort((a,b)=>b.rel-a.rel);for(const item of visible){const s=segmentAt(state.position+item.rel),p=project({x:0,y:s.p1.y,z:s.p1.z},state.x*ROAD,playerY+CAMERA_H,state.position),size=clamp(p.scale*ROAD*.19,15,255),cx=p.x+p.w*item.car.offset;if(carArt.complete){ctx.save();ctx.filter=`hue-rotate(${item.car.hue}deg) saturate(1.45) drop-shadow(0 10px 8px #000b)`;ctx.drawImage(carArt,cx-size/2,p.y-size*.61,size,size*.62);ctx.restore()}}const carSize=Math.min(width*.35,470),tilt=(state.keys.left||state.keys.a?-1:0)+(state.keys.right||state.keys.d?1:0);ctx.save();ctx.translate(width/2+tilt*16,height-carSize*.39);ctx.rotate(-tilt*.045);ctx.filter=`hue-rotate(${cars[state.car][4]}deg) saturate(1.32) drop-shadow(0 24px 20px #000c)`;ctx.drawImage(carArt,-carSize/2,-carSize*.31,carSize,carSize*.62);ctx.restore()}
function updateTraffic(dt){for(const car of state.traffic){const old=segmentAt(car.z);car.z=increase(car.z,car.speed*dt*21,state.track);const next=segmentAt(car.z);if(old!==next){const i=old.cars.indexOf(car);if(i>=0)old.cars.splice(i,1);next.cars.push(car)}const rel=(car.z-state.position+state.track)%state.track;if(rel<115&&!car.passed){car.passed=true;state.passes++}if(rel>900)car.passed=false}}
function update(dt){if(!state.racing||state.paused)return;const max=cars[state.car][2],boost=(state.keys.boost||state.keys[' '])&&state.boost>0,gas=state.keys.up||state.keys.w,brake=state.keys.down||state.keys.s,target=brake?18:(gas?max:max*.61),desired=boost?max*1.16:target;state.speed+=clamp(desired-state.speed,-max*1.8*dt,max*1.2*dt);state.speed=clamp(state.speed,0,max*1.16);const seg=segmentAt(state.position+PLAYER_Z),steer=(state.keys.left||state.keys.a?-1:0)+(state.keys.right||state.keys.d?1:0),sp=state.speed/max;state.x+=steer*dt*(1.7+sp)-seg.curve*sp*dt*.18;state.x=clamp(state.x,-1.25,1.25);if(Math.abs(state.x)>1)state.speed=Math.max(34,state.speed-max*dt*.42);state.boost=boost?Math.max(0,state.boost-dt*28):Math.min(100,state.boost+dt*9);state.position=increase(state.position,state.speed*dt*21,state.track);updateTraffic(dt);updateHud()}
function updateHud(){const p=state.track?state.position/state.track:0,check=Math.min(12,Math.floor(p*12)+1);$('#progress').style.width=(p*100)+'%';$('#checkpoint').textContent=String(check).padStart(2,'0')+' / 12';$('#speed').innerHTML=String(Math.round(state.speed)).padStart(3,'0')+' <em>MPH</em>';$('#boostValue').textContent=Math.round(state.boost)+'%';$('#boostBar').style.width=state.boost+'%';$('#position').textContent=String(Math.max(1,4-Math.floor(state.passes/5))).padStart(2,'0')+' / 04'}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(frame)}requestAnimationFrame(frame);$('#launch').onclick=launch;$('#resume').onclick=()=>{state.paused=false;show('none')};$('#restart').onclick=launch;$('#quit').onclick=()=>{state.racing=false;$('#app').classList.remove('engine-running');$('#hud').hidden=true;$('#boostHud').hidden=true;$('#touch').hidden=true;show('garage')};function key(e){return({arrowleft:'left',arrowright:'right',arrowup:'up',arrowdown:'down'}[e.key.toLowerCase()]||e.key.toLowerCase())}addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'&&state.racing){state.paused=!state.paused;show(state.paused?'pause':'none');return}const k=key(e);state.keys[k]=true;if(k==='shift')state.keys.boost=true;if(e.key===' ')state.keys[' ']=true});addEventListener('keyup',e=>{const k=key(e);state.keys[k]=false;if(k==='shift')state.keys.boost=false;if(e.key===' ')state.keys[' ']=false});$$('#touch button').forEach(b=>{const k=b.dataset.key,down=e=>{e.preventDefault();state.keys[k]=true},up=e=>{e.preventDefault();state.keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointerleave',up);b.addEventListener('pointercancel',up)});
})();
