(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={driver:0,car:0,route:0,racing:false,started:false,paused:false,speed:0,x:0,distance:0,boost:100,passes:0,keys:{},cars:[]};
const drivers=[['IZZY MONROE','IM','CURRENT RUNNER','ROUTE CURRENT','Finds the clearest way through the blackout.'],['AALIYAH GAIN','AG','VELOCITY','ACCELERATE','Turns every open street into an advantage.'],['THEO REED','TR','POWER LINE','BREAKAWAY','Keeps the rescue run moving forward.'],['JORDAN KIM','JK','SIGNAL TECH','OVERRIDE','Reads the city faster than it can close in.'],['MATEO RIVERA','MR','STREETWISE','SHORTCUT','Knows which streets still lead home.']];
const cars=[['VOLT GT','#50e7ed',184,'Twin-turbo street coupé',0],['NIGHTFALL R','#a47aff',176,'Low-slung grand tourer',68],['SUNFIRE ZX','#ff5b9e',191,'Lightweight sport compact',-48],['RIVET 4X','#ffbd4d',171,'All-weather rally machine',32]];
const routes=[['LAKEFRONT ESCAPE','Aldermoor → Lakefront Safe Zone','lakefront','Two laps · wet boulevard · marina lights','./art2d/lakefront.png'],['CASINO CAUSEWAY','Founders Square → Salk Bingo and Casino','casino','Two laps · tunnel sweep · casino express','./art2d/casino.png'],['LAMBEAU NIGHT RUN','Lambeau High → Clearview','lambeau','Two laps · stadium hill · lake curve','./art2d/lambeau.png']];
const canvas=$('#driveCanvas'),ctx=canvas.getContext('2d'),carArt=new Image(),backdrops=routes.map(r=>{let i=new Image();i.src=r[4];return i});carArt.src='./art2d/volt-gt.png';
let w=0,h=0,dpr=1,last=performance.now(),countdownTimer=0;const finishDistance=320000,drawDistance=170,segment=200;
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=Math.max(1,Math.round(w*dpr));canvas.height=Math.max(1,Math.round(h*dpr));ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function selectUI(){
 $('#drivers').innerHTML=drivers.map((d,i)=>`<button type="button" class="pick ${i===state.driver?'selected':''}" data-driver="${i}"><span class="tag">${d[2]}</span><span class="initial">${d[1]}</span><h3>${d[0]}</h3><p>${d[4]}</p><small class="ability">⚡ ${d[3]}</small></button>`).join('');
 $('#cars').innerHTML=cars.map((c,i)=>`<button type="button" class="pick car-pick ${i===state.car?'selected':''}" data-car="${i}" style="--car-hue:${c[4]}deg;--car-glow:${c[1]}"><img src="./art2d/volt-gt.png" alt="${c[0]}"><span class="tag">ORIGINAL 1999 SPORTS CAR</span><h3>${c[0]}</h3><p>${c[3]}</p><div class="stat">TOP ${c[2]} MPH<br>GRIP ${'▮'.repeat(3+i%2)}</div></button>`).join('');
 $('#routeCards').innerHTML=routes.map((r,i)=>`<button type="button" class="route-card ${i===state.route?'selected':''}" data-route="${i}" style="--route-img:url('${r[4]}')"><div><span class="tag">${r[3].toUpperCase()}</span><h3>${r[0]}</h3><p>${r[1]}</p><small>12 CHECKPOINTS · PASSENGER ABOARD FROM START</small></div></button>`).join('');
 $$('[data-driver]').forEach(b=>b.onclick=()=>{state.driver=+b.dataset.driver;selectUI()});$$('[data-car]').forEach(b=>b.onclick=()=>{state.car=+b.dataset.car;selectUI()});$$('[data-route]').forEach(b=>b.onclick=()=>{state.route=+b.dataset.route;selectUI()});
}selectUI();
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));if(id!=='none')$('#'+id).classList.add('active')}window.sparkedShow=show;document.addEventListener('click',e=>{let b=e.target.closest('[data-screen]');if(b){e.preventDefault();show(b.dataset.screen)}});
function makeTraffic(){state.cars=[];for(let i=0;i<5;i++)state.cars.push({z:2800+i*5100,offset:[-.58,.48,-.18,.72,-.76][i],speed:118+i*12,hue:[62,288,126,18,190][i],passed:false});}
function launch(){Object.assign(state,{racing:true,started:false,paused:false,speed:0,x:0,distance:0,boost:100,passes:0,keys:{}});makeTraffic();$('#app').className='route-'+routes[state.route][2]+' engine-running';$('#routeName').textContent=routes[state.route][0];$('#hud').hidden=false;$('#boostHud').hidden=false;$('#touch').hidden=innerWidth>720;show('none');countdownTimer=3;$('#countdown').textContent='3';$('#countdown').classList.add('show');}
function roadCenter(worldZ,depth){return w*.5+Math.sin(worldZ/13500)*w*.18*depth*depth+Math.sin(worldZ/4800)*w*.045*depth*depth-state.x*w*.13*depth}
function cover(image){if(!image.complete||!image.naturalWidth)return;let s=Math.max(w/image.naturalWidth,h/image.naturalHeight),iw=image.naturalWidth*s,ih=image.naturalHeight*s;ctx.drawImage(image,(w-iw)/2,(h-ih)/2,iw,ih)}
function quad(x1,y1,x2,y2,x3,y3,x4,y4,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.lineTo(x3,y3);ctx.lineTo(x4,y4);ctx.closePath();ctx.fill()}
function render(){ctx.clearRect(0,0,w,h);if(!state.racing)return;cover(backdrops[state.route]);ctx.fillStyle='rgba(5,7,20,.42)';ctx.fillRect(0,0,w,h);if(!state.started)return;let horizon=h*.31;
 for(let n=drawDistance;n>0;n--){let near=n/drawDistance,far=(n+1)/drawDistance,zn=state.distance+n*segment,zf=state.distance+(n+1)*segment,yn=horizon+(h-horizon)*near*near,yf=horizon+(h-horizon)*far*far,hn=w*(.055+.60*near*near),hf=w*(.055+.60*far*far),cn=roadCenter(zn,near),cf=roadCenter(zf,far),alt=(Math.floor((state.distance+n*segment)/segment/3)%2===0);quad(cf-hf,yf,cf+hf,yf,cn+hn,yn,cn-hn,yn,alt?'#161a2b':'#111523');quad(cf-hf-15*far,yf,cf-hf,yf,cn-hn,yn,cn-hn-15*near,yn,alt?'#f2b34e':'#81407d');quad(cf+hf,yf,cf+hf+15*far,yf,cn+hn+15*near,yn,cn+hn,yn,alt?'#f2b34e':'#81407d');if(n%6<3){for(let lane=-1;lane<=1;lane+=2){let a=cn+lane*hn/3,b=cf+lane*hf/3;quad(b-2*far,yf,b+2*far,yf,a+2*near,yn,a-2*near,yn,'rgba(255,240,190,.82)')}}}
 let visible=[];for(let car of state.cars){let rel=(car.z-state.distance+finishDistance)%finishDistance;if(rel<drawDistance*segment)visible.push({car,rel})}visible.sort((a,b)=>b.rel-a.rel);for(let item of visible){let d=1-item.rel/(drawDistance*segment),y=horizon+(h-horizon)*d*d,half=w*(.055+.60*d*d),x=roadCenter(state.distance+item.rel,d)+item.car.offset*half*.64,size=28+d*d*220;if(carArt.complete){ctx.save();ctx.filter=`hue-rotate(${item.car.hue}deg) saturate(1.38) drop-shadow(0 12px 8px #0009)`;ctx.drawImage(carArt,x-size*.5,y-size*.30,size,size*.62);ctx.restore()}}
 let psize=Math.min(w*.33,470),px=w*.5+state.x*w*.25,py=h-psize*.44;ctx.save();ctx.filter=`hue-rotate(${cars[state.car][4]}deg) saturate(1.3) drop-shadow(0 22px 20px #000b)`;ctx.translate(px,py);ctx.rotate(-state.x*.07);ctx.drawImage(carArt,-psize*.5,-psize*.31,psize,psize*.62);ctx.restore();
}
function update(dt){if(!state.racing)return;if(!state.started){countdownTimer-=dt;if(countdownTimer<=0){state.started=true;$('#countdown').classList.remove('show')}else $('#countdown').textContent=Math.ceil(countdownTimer);return}if(state.paused)return;let max=cars[state.car][2],boost=(state.keys.boost||state.keys[' '])&&state.boost>0,throttle=state.keys.up||state.keys.w,brake=state.keys.down||state.keys.s,target=brake?28:(throttle?max:(max*.62));if(boost)target=max*1.18;state.speed+=(target-state.speed)*dt*(brake?2.7:1.25);state.speed=Math.max(0,Math.min(max*1.18,state.speed));let steer=(state.keys.left||state.keys.a?-1:0)+(state.keys.right||state.keys.d?1:0);state.x=Math.max(-1.18,Math.min(1.18,state.x+steer*dt*(1.4+state.speed/max)));if(boost)state.boost=Math.max(0,state.boost-dt*30);else state.boost=Math.min(100,state.boost+dt*10);state.distance+=state.speed*dt*21;for(let car of state.cars){car.z=(car.z+car.speed*dt*17)%finishDistance;let rel=(car.z-state.distance+finishDistance)%finishDistance;if(rel<180&&Math.abs(car.offset-state.x)<.23){state.speed*=.56;state.boost=Math.max(0,state.boost-14)}if(rel<90&&!car.passed){car.passed=true;state.passes++}if(rel>1000)car.passed=false}if(state.distance>=finishDistance){finish();return}updateHud();}
function updateHud(){let progress=Math.min(1,state.distance/finishDistance),check=Math.min(12,Math.floor(progress*12)+1);$('#progress').style.width=(progress*100)+'%';$('#checkpoint').textContent=String(check).padStart(2,'0')+' / 12';$('#speed').innerHTML=String(Math.round(state.speed)).padStart(3,'0')+' <em>MPH</em>';$('#boostValue').textContent=Math.round(state.boost)+'%';$('#boostBar').style.width=state.boost+'%';$('#position').textContent=String(Math.max(1,4-Math.floor(state.passes/3))).padStart(2,'0')+' / 04'}
function finish(){state.racing=false;state.started=false;$('#app').classList.remove('engine-running');$('#hud').hidden=true;$('#boostHud').hidden=true;$('#touch').hidden=true;$('#finishCopy').innerHTML=`<p>SAFE ZONE REACHED</p><h2>YOU GOT THEM HOME.</h2><span>${drivers[state.driver][0].split(' ')[0]} made it through ${routes[state.route][0]}. The race never stopped.</span><div class="result-stats">12 / 12 CHECKPOINTS · ${state.passes} CLEAN PASSES · ${Math.round(state.boost)}% SPARK REMAINING</div><button class="primary" id="again">RUN ANOTHER ROUTE <b>→</b></button>`;show('finish');$('#again').onclick=()=>show('routes')}
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(frame)}requestAnimationFrame(frame);
$('#launch').onclick=launch;$('#resume').onclick=()=>{state.paused=false;show('none')};$('#restart').onclick=launch;$('#quit').onclick=()=>{state.racing=false;state.started=false;$('#hud').hidden=true;$('#boostHud').hidden=true;show('garage')};
function key(e){return({arrowleft:'left',arrowright:'right',arrowup:'up',arrowdown:'down'}[e.key.toLowerCase()]||e.key.toLowerCase())}addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'&&state.racing){state.paused=!state.paused;show(state.paused?'pause':'none');return}let k=key(e);state.keys[k]=true;if(k==='shift')state.keys.boost=true;if(e.key===' ')state.keys[' ']=true});addEventListener('keyup',e=>{let k=key(e);state.keys[k]=false;if(k==='shift')state.keys.boost=false;if(e.key===' ')state.keys[' ']=false});$$('#touch button').forEach(b=>{let k=b.dataset.key,down=e=>{e.preventDefault();state.keys[k]=true},up=e=>{e.preventDefault();state.keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointerleave',up);b.addEventListener('pointercancel',up)});
})();
