import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={driver:0,car:0,route:0,racing:false,started:false,paused:false,progress:0,speed:0,boost:100,elapsed:0,passes:0,checkpoint:0,keys:{},traffic:[],health:100};
const drivers=[['IZZY MONROE','IM','CURRENT RUNNER','ROUTE CURRENT','Finds the clearest way through the blackout.'],['AALIYAH GAIN','AG','VELOCITY','ACCELERATE','Turns every open street into an advantage.'],['THEO REED','TR','POWER LINE','BREAKAWAY','Keeps the rescue run moving forward.'],['JORDAN KIM','JK','SIGNAL TECH','OVERRIDE','Reads the city faster than it can close in.'],['MATEO RIVERA','MR','STREETWISE','SHORTCUT','Knows which streets still lead home.']];
const cars=[['VOLT GT','#50e7ed','#125f87',184,1.1,'Twin-turbo street coupé'],['NIGHTFALL R','#a47aff','#4f2885',176,1.24,'Low-slung grand tourer'],['SUNFIRE ZX','#ff5b9e','#8b1f54',191,.98,'Lightweight sport compact'],['RIVET 4X','#ffbd4d','#9b5014',171,1.42,'All-weather rally machine']];
const routes=[
 {name:'LAKEFRONT ESCAPE',sub:'Aldermoor → Lakefront Safe Zone',note:'Two laps · wet boulevard · marina lights',laps:2,sky:0x41235e,land:0x15243b,water:true,pts:[[0,0],[210,-35],[370,-180],[250,-390],[-40,-420],[-310,-315],[-360,-65],[-255,155],[-15,205],[220,135]]},
 {name:'CASINO CAUSEWAY',sub:'Founders Square → Salk Bingo & Casino',note:'Two laps · casino curve · tunnel straight',laps:2,sky:0x192554,land:0x202344,casino:true,pts:[[0,0],[285,40],[425,-150],[335,-350],[40,-430],[-280,-375],[-420,-130],[-370,145],[-130,290],[170,245],[330,130]]},
 {name:'LAMBEAU NIGHT RUN',sub:'Lambeau High → Clearview',note:'Two laps · hill run · Clearview sweep',laps:2,sky:0x123953,land:0x112a3c,school:true,pts:[[0,0],[195,170],[420,95],[460,-145],[290,-330],[0,-410],[-280,-280],[-405,-45],[-255,190],[-25,270]]}
];
const canvas=$('#game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(62,1,.1,2000),clock=new THREE.Clock();let world,curve,curveLength,player,carGlow,ambient,routeData;
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function chooseUI(){
 $('#drivers').innerHTML=drivers.map((d,i)=>`<button class="pick ${i===state.driver?'selected':''}" data-driver="${i}"><span class="tag">${d[2]}</span><span class="initial">${d[1]}</span><h3>${d[0]}</h3><p>${d[4]}</p><small class="ability">⚡ ${d[3]}</small></button>`).join('');
 $('#cars').innerHTML=cars.map((c,i)=>`<button class="pick car-pick ${i===state.car?'selected':''}" data-car="${i}"><div class="car-drawing" style="background:linear-gradient(145deg,#fff,${c[1]} 35%,${c[2]} 76%)"><i></i><b></b></div><span class="tag">SPORTS CAR / 1999</span><h3>${c[0]}</h3><p>${c[5]}</p><div class="spec">TOP ${c[3]} MPH<br>GRIP ${'▮'.repeat(Math.round(c[4]*4))}</div></button>`).join('');
 $('#routesList').innerHTML=routes.map((r,i)=>`<button class="route ${i===state.route?'selected':''}" data-route="${i}"><span class="tag">${r.note.toUpperCase()}</span><h3>${r.name}</h3><p>${r.sub}</p><small>12 CHECKPOINTS · PASSENGER ABOARD FROM START</small></button>`).join('');
 $$('[data-driver]').forEach(b=>b.onclick=()=>{state.driver=+b.dataset.driver;chooseUI()});$$('[data-car]').forEach(b=>b.onclick=()=>{state.car=+b.dataset.car;chooseUI()});$$('[data-route]').forEach(b=>b.onclick=()=>{state.route=+b.dataset.route;chooseUI()});
}chooseUI();
function show(id){$$('.screen').forEach(e=>e.classList.remove('active'));if(id!=='none')$('#'+id).classList.add('active')}$$('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));
function mat(color,emissive=0){return new THREE.MeshStandardMaterial({color,roughness:.62,metalness:.25,emissive:color,emissiveIntensity:emissive})}
function roadMesh(offset,width,color,y=.03){const steps=520,v=[],idx=[];for(let i=0;i<=steps;i++){let t=i/steps,p=curve.getPointAt(t),tan=curve.getTangentAt(t).normalize(),side=new THREE.Vector3(-tan.z,0,tan.x),a=p.clone().addScaledVector(side,offset-width/2),b=p.clone().addScaledVector(side,offset+width/2);v.push(a.x,y,a.z,b.x,y,b.z)}for(let i=0;i<steps;i++)idx.push(i*2,i*2+1,i*2+2,i*2+1,i*2+3,i*2+2);let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();return new THREE.Mesh(g,mat(color,0))}
function makeCar(color,dark,scale=1){let g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(2.25, .48,4.6),mat(color,.08)),hood=new THREE.Mesh(new THREE.BoxGeometry(2.12,.23,1.4),mat(color,.06)),glass=new THREE.Mesh(new THREE.BoxGeometry(1.62,.58,1.9),new THREE.MeshStandardMaterial({color:0x9de6ff,roughness:.15,metalness:.75,emissive:0x265071,emissiveIntensity:.22}));body.position.y=.48;hood.position.set(0,.77,-1.28);glass.position.set(0,1.02,.3);g.add(body,hood,glass);let wheelMat=mat(0x080a12);for(const x of[-1.13,1.13])for(const z of[-1.42,1.42]){let w=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.28,14),wheelMat);w.rotation.z=Math.PI/2;w.position.set(x,.35,z);g.add(w)}let lights=mat(0xbefaff,1.5);for(const x of[-.72,.72]){let l=new THREE.Mesh(new THREE.BoxGeometry(.36,.15,.06),lights);l.position.set(x,.66,-2.33);g.add(l)}g.scale.setScalar(scale);g.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true}});return g}
function building(pos,side,i){let h=10+(i%8)*7,w=5+(i%4)*3,d=5+((i*7)%4)*3,m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(i%3?0x1b203a:0x2d2343,.05));m.position.copy(pos).addScaledVector(side,20+(i%5)*8);m.position.y=h/2;m.castShadow=m.receiveShadow=true;world.add(m);let windows=new THREE.Mesh(new THREE.BoxGeometry(w+.04,h*.72,.05),mat(i%3?0xffbe6d:0x8d7dff,.35));windows.position.copy(m.position);windows.position.z+=side.z>0?d/2+.03:-d/2-.03;world.add(windows)}
function lamp(pos,side){let g=new THREE.Group(),pole=new THREE.Mesh(new THREE.CylinderGeometry(.12,.16,6,8),mat(0x24283a)),bulb=new THREE.Mesh(new THREE.SphereGeometry(.34,10,8),mat(0xffd989,2));pole.position.y=3;bulb.position.y=6.1;g.add(pole,bulb);g.position.copy(pos).addScaledVector(side,11);world.add(g)}
function buildWorld(){if(world)scene.remove(world);world=new THREE.Group();scene.add(world);let r=routes[state.route];scene.background=new THREE.Color(r.sky);scene.fog=new THREE.FogExp2(r.sky,.0028);curve=new THREE.CatmullRomCurve3(r.pts.map(([x,z],i)=>new THREE.Vector3(x,3+Math.sin(i*.8)*3,z)),true,'catmullrom',.16);curveLength=curve.getLength();routeData=r;let ground=new THREE.Mesh(new THREE.PlaneGeometry(1800,1800),mat(r.land));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);if(r.water){let water=new THREE.Mesh(new THREE.PlaneGeometry(1200,650),mat(0x244b75,.22));water.rotation.x=-Math.PI/2;water.position.set(160,.03,-450);world.add(water)}world.add(roadMesh(0,17,0x1c202b,.06),roadMesh(-7.9,.42,0xffd98a,.09),roadMesh(7.9,.42,0xffd98a,.09),roadMesh(0,.35,0xf7f3c7,.10));for(let i=0;i<110;i++){let t=i/110,p=curve.getPointAt(t),tan=curve.getTangentAt(t).normalize(),side=new THREE.Vector3(-tan.z,0,tan.x);building(p,side,i);if(i%4===0)lamp(p,side);if(i%4===1)lamp(p,side.clone().multiplyScalar(-1))}if(r.casino){let tower=new THREE.Mesh(new THREE.BoxGeometry(34,56,26),mat(0x342059,.15));tower.position.set(35,28,-450);world.add(tower);let sign=new THREE.Mesh(new THREE.BoxGeometry(22,6,.5),mat(0xff4ca2,1));sign.position.set(35,48,-463.3);world.add(sign)}if(r.school){let sign=new THREE.Mesh(new THREE.BoxGeometry(40,8,2),mat(0x6444a4,.3));sign.position.set(420,15,94);world.add(sign)}let start=curve.getPointAt(0);let startGate=new THREE.Mesh(new THREE.TorusGeometry(9,.35,10,32,Math.PI),mat(0x5cebe5,1));startGate.rotation.y=Math.PI/2;startGate.position.copy(start);startGate.position.y=9;world.add(startGate);}
function setCarAt(obj,t,lane=0){let u=(t%1+1)%1,p=curve.getPointAt(u),tan=curve.getTangentAt(u).normalize(),side=new THREE.Vector3(-tan.z,0,tan.x);obj.position.copy(p).addScaledVector(side,lane);obj.position.y+=.62;obj.rotation.y=Math.atan2(tan.x,tan.z)}
function createRace(){buildWorld();player=makeCar(cars[state.car][1],cars[state.car][2],1.12);world.add(player);carGlow=new THREE.PointLight(cars[state.car][1],2.6,32,2);player.add(carGlow);carGlow.position.set(0,2,1);state.traffic=[];for(let i=0;i<5;i++){let ai={p:.045+i*.125,lane:(i%3-1)*3.8,speed:.72+i*.045,car:makeCar(cars[(i+1)%cars.length][1],cars[(i+1)%cars.length][2],.94),hit:0};world.add(ai.car);state.traffic.push(ai)}setCarAt(player,0,0);}
function startRace(){Object.assign(state,{racing:true,started:false,paused:false,progress:0,speed:0,boost:100,elapsed:0,passes:0,checkpoint:0,health:100});createRace();$('#routeTitle').textContent=routeData.name;$('#objective').textContent='PASSENGER ABOARD · GET TO THE SAFE ZONE';$('#hud').hidden=false;$('#boostHud').hidden=false;$('#touch').hidden=innerWidth>720;countdown(3)}
function countdown(n){let c=$('#countdown');c.classList.add('show');c.textContent=n?' '+n:'GO!';setTimeout(()=>{if(n>0)countdown(n-1);else{c.classList.remove('show');state.started=true}},720)}
function updateHUD(){let done=Math.min(1,state.progress/routeData.laps),next=Math.min(12,Math.floor(done*12)+1);$('#progress').style.width=done*100+'%';$('#checkpoints').textContent=String(next).padStart(2,'0')+' / 12';$('#speed').innerHTML=String(Math.round(state.speed)).padStart(3,'0')+' <em>MPH</em>';$('#boostValue').textContent=Math.round(state.boost)+'%';$('#boostBar').style.width=state.boost+'%';let ahead=state.traffic.filter(a=>a.p>state.progress).length;$('#position').textContent=String(Math.max(1,ahead+1)).padStart(2,'0')+' / 04'}
function finish(){state.racing=false;state.started=false;$('#hud').hidden=true;$('#boostHud').hidden=true;$('#touch').hidden=true;$('#finishText').innerHTML=`<p>SAFE ZONE REACHED</p><h2>YOU GOT THEM HOME.</h2><span>${drivers[state.driver][0].split(' ')[0]} brought the passenger through ${routeData.name} in ${Math.floor(state.elapsed/60)}:${String(Math.floor(state.elapsed%60)).padStart(2,'0')}. The race never stopped.</span><div class="result-stats">12 / 12 CHECKPOINTS · ${state.passes} CLEAN OVERTAKES · ${Math.round(state.health)}% CAR CONDITION</div><button class="primary" id="again">RUN ANOTHER ROUTE <b>→</b></button>`;show('finish');$('#again').onclick=()=>show('routes')}
function update(dt){if(!state.racing||!state.started||state.paused)return;let c=cars[state.car],boost=(state.keys.boost||state.keys[' '])&&state.boost>1,brake=state.keys.brake||state.keys.down||state.keys.s,go=state.keys.up||state.keys.w||state.keys.left||state.keys.right||state.keys.a||state.keys.d||!brake,target=brake?55:c[3]*(boost?1.22:1);state.speed+=(target-state.speed)*dt*(go?1.22:.75);state.speed=Math.max(15,state.speed);let steer=(state.keys.left||state.keys.a?-1:0)+(state.keys.right||state.keys.d?1:0);state.lane=THREE.MathUtils.clamp((state.lane||0)+steer*dt*9,-6.4,6.4);if(boost)state.boost=Math.max(0,state.boost-dt*27);else state.boost=Math.min(100,state.boost+dt*8);state.progress+=state.speed*dt/15800;state.elapsed+=dt;setCarAt(player,state.progress,state.lane);for(const ai of state.traffic){ai.p+=dt*ai.speed*.023;if(ai.p<state.progress-.08){ai.p+=routeData.laps;state.passes++}setCarAt(ai.car,ai.p,ai.lane);let pd=Math.abs((ai.p%routeData.laps)-(state.progress%routeData.laps));if(pd<.004&&Math.abs(ai.lane-state.lane)<2.5&&ai.hit<=0){ai.hit=.6;state.speed*=.68;state.health=Math.max(25,state.health-7);state.lane+=state.lane>ai.lane?1:-1}ai.hit-=dt}let p=curve.getPointAt(state.progress%1),t=curve.getTangentAt(state.progress%1).normalize(),look=p.clone().addScaledVector(t,21);camera.position.lerp(p.clone().addScaledVector(t,-15).add(new THREE.Vector3(0,8.5,0)).add(new THREE.Vector3(-t.z,0,t.x).multiplyScalar(state.lane*.18)),1-Math.exp(-dt*5));camera.lookAt(look);let cp=Math.min(12,Math.floor(state.progress/routeData.laps*12));if(cp>state.checkpoint){state.checkpoint=cp;state.boost=Math.min(100,state.boost+11)}if(state.progress>=routeData.laps)finish();updateHUD()}
ambient=new THREE.HemisphereLight(0x8fb8ff,0x111522,2.3);scene.add(ambient);let sun=new THREE.DirectionalLight(0xffbd82,2.4);sun.position.set(-160,260,70);sun.castShadow=true;scene.add(sun);scene.add(new THREE.PointLight(0x7568ff,1.6,500));
function loop(){let dt=Math.min(clock.getDelta(),.05);update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}loop();
$('#launch').onclick=startRace;$('#resume').onclick=()=>{state.paused=false;show('none')};$('#restart').onclick=startRace;$('#quit').onclick=()=>{state.racing=false;state.started=false;$('#hud').hidden=true;$('#boostHud').hidden=true;show('garage')};
function keyName(e){return({arrowleft:'left',arrowright:'right',arrowup:'up',arrowdown:'down'}[e.key.toLowerCase()]||e.key.toLowerCase())}addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Escape'].includes(e.key))e.preventDefault();if(e.key==='Escape'&&state.racing){state.paused=!state.paused;if(state.paused)show('pause');else show('none');return}let k=keyName(e);state.keys[k]=true;if(k==='shift')state.keys.boost=true;if(e.key===' ')state.keys[' ']=true});addEventListener('keyup',e=>{let k=keyName(e);state.keys[k]=false;if(k==='shift')state.keys.boost=false;if(e.key===' ')state.keys[' ']=false});$$('#touch button').forEach(b=>{let k=b.dataset.key,down=e=>{e.preventDefault();state.keys[k]=true},up=e=>{e.preventDefault();state.keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointerleave',up);b.addEventListener('pointercancel',up)});
